name = "gpt-telegram-worker"
main = "src/index.ts"
compatibility_date = "2024-09-29"
account_id = ""
workers_dev = true

[vars]
TELEGRAM_BOT_TOKEN = ""
WHITELISTED_USERS = ""
UPSTASH_REDIS_REST_URL = ""
UPSTASH_REDIS_REST_TOKEN = ""
GOOGLE_MODEL_KEY = ""
GOOGLE_MODEL_BASEURL = "https://generativelanguage.googleapis.com/v1beta"
GOOGLE_MODELS = "gemini-2.0-flash-exp"
DEFAULT_MODEL = "gemini-2.0-flash-exp"
SYSTEM_INIT_MESSAGE_ROLE = "system"
BOT_NAME = "" # bot名称
GROUP_COOLDOWN_INTERVAL = "180000" # 冷却间隔，单位毫秒

[[kv_namespaces]]
binding = "COOLDOWN"
id = ""

[[kv_namespaces]]
binding = "SYSTEM_INIT_MESSAGE"
id = ""

[observability]
enabled = true
head_sampling_rate = 1




